--- 
abstract: Lazy evaluation in Perl
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Scalar-Defer
no_index: 
  directory: 
    - inc
    - t
provides: 
  Scalar::Defer: 
    file: lib/Scalar/Defer.pm
    version: 0.15
  Scalar::Defer::Deferred: 
    file: lib/Scalar/Defer.pm
requires: 
  Class::InsideOut: 0
  Exporter::Lite: 0
  perl: 5.6.0
version: 0.15
