abstract: Calculate values on demand
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.63
license: MIT
name: Scalar-Defer
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::InsideOut: 0
  Exporter::Lite: 0
  perl: 5.6.0
version: 0.02
